-- Programmers Lv 4. 그룹별 조건에 맞는 식당 목록 출력하기.
-- https://school.programmers.co.kr/learn/courses/30/lessons/131124
-- MAX(CNT) 구하는 것이 주요 문제.

WITH RR AS (
    SELECT MEMBER_ID, COUNT(MEMBER_ID) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
                      JOIN RR ON M.MEMBER_ID = RR.MEMBER_ID
WHERE RR.CNT = (SELECT MAX(CNT) FROM RR)
ORDER BY REVIEW_DATE, REVIEW_TEXT;